stages:
  - build
  - upload

build:
  stage: build
  image: node:18.15-alpine3.16
  script:
    - npm ci
    - npm build
  artifacts:
    paths:
      - /public

upload:
  stage: upload
  image: alpine:stable
  script:
    - apk add lftp
    - lftp --version
    - lftp -c "set ftp:ssl-force true; set ssl:verify-certificate false; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOSTNAME; mirror -Renv ./public ./htdocs"
  needs:
    - job: build
      artifacts: true