build:
  image: node:stable
  stage: build
  script:
    - npm ci
    - apk add lftp
    - lftp --version
    - lftp -c "set ftp:ssl-force true; set ssl:verify-certificate false; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOSTNAME; mirror -Renv ./public ./htdocs"
