stages:
  - build
  - upload

build:
  stage: build
  image: node:18.15-alpine3.16
  script:
    - npm ci --silent
    - npm run build
  artifacts:
    paths:
      - public/

upload:
  stage: upload
  image: alpine:3.17
  script:
    - apk add lftp
    - lftp --version
    - ls -la ./public
    - echo "Uploading files to $FTP_HOSTNAME"
    - lftp -c "open $FTP_HOSTNAME; user $FTP_USERNAME $FTP_PASSWORD; mirror --reverse ./public /htdocs"
  needs:
    - job: build
      artifacts: true